version: '3.4'

services:
  bookstore:
    image: bookstore
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - database

        # redis config
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    volumes:
      - redis:/data
  # database config
  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: booksStore
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  redis:
